#Basics of Arrays

In [ ]:
import numpy as np
import sys

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([4,3,2,1])

In [ ]:
a[0]

4

In [ ]:
a[1:]

array([3, 2, 1])

In [ ]:
a[1:3]

array([3, 2])

In [ ]:
a[1:-1]

array([3, 2])

In [ ]:
b = np.array([0.00000002,0.5,-1.2,2,3])

In [ ]:
b[0],b[4]

(2e-08, 3.0)

In [ ]:
b[[0,4]]

array([2.e-08, 3.e+00])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
c = np.array([1.2,3.2,4,5,8.99999],dtype=np.int64)

In [ ]:
c

array([1, 3, 4, 5, 8])

In [ ]:
d = np.array(['a','b','c'])
print(d)
d.dtype

['a' 'b' 'c']


dtype('<U1')

#Shapes and Dimensions

In [ ]:
A = np.array([[1,2,3,4],
              [10,21,22,23]])
print(A)

[[ 1  2  3  4]
 [10 21 22 23]]


In [ ]:
A.shape

(2, 4)

In [ ]:
A.ndim

2

In [ ]:
A.size

8

In [ ]:
B = np.array([
              [
               [1,2,3,4],
               [5,6,7,8]
              ],
              [
               [10,11,12,13],
               [19,21,22,23]
              ]
              ])
print(B)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 11 12 13]
  [19 21 22 23]]]


In [ ]:
B.shape

(2, 2, 4)

In [ ]:
B.ndim

3

In [ ]:
B.size

16

#Getting Familiar with Marix Indices

In [ ]:
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [ ]:
m[0]

array([1, 2, 3])

In [ ]:
m[0][1] #0th row 2nd column element

2

In [ ]:
m[0,1] # m(dimension 1, dimension 2, d3, d4......)

2

In [ ]:
m[1:] #Print elements from 2nd column

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
m[1:,1:] #printing all elements from 2nd column and 2nd row onwards

array([[5, 6],
       [8, 9]])

In [ ]:
m[:2,:2] #printing rows till 1st column and 1st row

array([[1, 2],
       [4, 5]])

In [ ]:
m[2] = [1,2,3]

In [ ]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [ ]:
m[2] = 99.9
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

#Summary Statistics

In [ ]:
s = np.array([4,5,6,7,8])

In [ ]:
s.sum()

30

In [ ]:
s.mean()

6.0

In [ ]:
s.var()

2.0

In [ ]:
s.std()

1.4142135623730951

In [ ]:
S = np.array([[1,10,99],
              [11,32,12],
              [43,21,32]])

In [ ]:
S.sum()

261

In [ ]:
S.mean()

29.0

In [ ]:
S.std()

27.760883751542686

In [ ]:
S.var()

770.6666666666666

In [ ]:
S.sum(axis=0) #Sum Column Wise (Dimension wise)

array([ 55,  63, 143])

In [ ]:
S.sum(axis=1) #Sum Row wise (Dimension Wise)

array([110,  55,  96])

#Broadcasting and Vectorized Arrays

In [ ]:
v = np.arange(4)
v

array([0, 1, 2, 3])

In [ ]:
v+10

array([10, 11, 12, 13])

In [ ]:
v*10

array([ 0, 10, 20, 30])

In [ ]:
v #Real values won't be modified

array([0, 1, 2, 3])

In [ ]:
v+= 100 #Now the values will be modified
v

array([200, 201, 202, 203])

In [ ]:
l = [1,2,3,4]
l*4 #There will be an error if we do l+4 like this

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
[i* 4 for i in l] 

[4, 8, 12, 16]

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v1+v2

array([ 6,  8, 10, 12])

In [ ]:
v3 = np.dot(v1,v2)
v3

70

#Boolean Arrays (V.Important)

In [ ]:
bo = np.arange(4)
bo

array([0, 1, 2, 3])

In [ ]:
bo[0], bo[-1] #Traditional Way of selecting

(0, 3)

In [ ]:
bo[[0,-1]] #Modern Way

array([0, 3])

In [ ]:
bo [[True,False,False,True]] #Brand New Way

array([0, 3])

In [ ]:
bo >= 2

array([False, False,  True,  True])

In [ ]:
bo[bo>=2]

array([2, 3])

In [ ]:
bo.mean()

1.5

In [ ]:
bo[bo>bo.mean()]

array([2, 3])

In [ ]:
bo[(bo==1) | (bo==3)]

array([1, 3])

In [ ]:
bo[(bo<=1) & (bo % 2 ==0)]

array([0])

In [ ]:
r = np.random.randint(50,size=(3,3))
r

array([[ 6, 49, 25],
       [20, 47, 17],
       [37, 34, 48]])

In [ ]:
r > 25

array([[False,  True, False],
       [False,  True, False],
       [ True,  True,  True]])

In [ ]:
r[r>25]

array([49, 47, 37, 34, 48])

#Linear Algebra

In [ ]:
la = np.random.randint(50,size=(3,3))
la

array([[ 6, 13, 25],
       [44, 38, 40],
       [15,  3, 28]])

In [ ]:
la2 = np.random.randint(50,size=(2,3))
la2

array([[44,  1, 34],
       [44, 35, 29]])

In [ ]:
la.dot(la2.T) #Transposing la2 for Matrix Multiplication

array([[1127, 1444],
       [3334, 4426],
       [1615, 1577]])

In [ ]:
la2 @ la #Cross Product

array([[ 818,  712, 2092],
       [2239, 1989, 3312]])

#Size of Object in Python and Comparision of the Size by using NumPy

In [ ]:
sys.getsizeof(1) #O/p is in Bytes 

28

In [ ]:
sys.getsizeof(99**99999)

88416

In [ ]:
np.dtype(np.int8).itemsize #We can easily see the difference b/w normal python and after using NumPy

1

In [ ]:
np.dtype(float).itemsize

8

In [ ]:
#Lets see the size of lists
sys.getsizeof([1,2])

88

In [ ]:
np.array([1,2]).itemsize #We can how much size we have saved 80 bytes

8

#Lets see the difference in the performance

In [ ]:
l = list(range(10000))

In [ ]:
n = np.arange(10000)

In [ ]:
%time np.sum(n ** 2)

CPU times: user 232 µs, sys: 0 ns, total: 232 µs
Wall time: 240 µs


333283335000

In [ ]:
%time sum([i ** 2 for i in l])

CPU times: user 3.36 ms, sys: 1.08 ms, total: 4.44 ms
Wall time: 4.93 ms


333283335000